#!/usr/bin/env sh
ln -sf /opt/CloudOTP/CloudOTP /usr/bin/CloudOTP
chmod +x /usr/bin/CloudOTP
update-mime-database /usr/share/mime || true
update-desktop-database /usr/share/applications || true
exit 0