#!/usr/bin/env sh
ln -sf /opt/CloudOTP/cloudotp /usr/bin/cloudotp
chmod +x /usr/bin/cloudotp
update-mime-database /usr/share/mime || true
update-desktop-database /usr/share/applications || true
exit 0